version: '3'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9006:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
